export const MESSAGES = {
  SUCCESS: 'Success',
  ERROR: 'Error',
  TOKEN: {
    INVALID: 'Invalid token.',
    NOT_FOUND: 'Token not found.',
    NOT_ADD_TOKEN: 'Cannot add new token.',
    VERIFIED: 'This user has already been verified.',
  },
  AUTHENTICATION: {
    INVALID_PASSWORD: 'Password is invalid.',
    PASSWORD_NOT_MATCH: 'Password not match',
    FORBIDDEN: 'You don’t have permission to access',
  },
  USER: {
    NOT_FOUND_EMAIL: 'Email is invalid.',
    EXISTED_EMAIL: 'Email address you have entered is already associated with another account.',
    NOT_EXIST: "User isn't exist.",
    REGISTER_VERIFY: 'A verification email has been sent to ',
    FORGOT_PASSWORD: 'A reset password email has been sent to ',
    CHANGE_PASSWORD_SUCCESS: 'Change password successfully!',
    RESET_PASSWORD_FAILED: 'Password changed failed!',
    RESET_PASSWORD_SUCCESS: 'Password changed successfully. Please login with your new password.',
    ISVERIFIED: 'The account has been verified. Please log in.',
    NOT_VERIFY: 'The account is unverified. Please verify your account!',
    CREATED_SUCCESSFULLY: 'Create User successfully!',
    UPDATED_SUCCESSFULLY: 'Update User successfully!',
    GET_DATA_SUCCESSFULLY: 'Get User data successfully!',
    DELETED_SUCCESSFULLY: 'Delete User successfully!',
  },
  REWARD: {
    NOT_EXIST: "Reward isn't exist.",
    EXISTED: "Reward's name exists.",
    CREATED_SUCCESSFULLY: 'Create Reward successfully!',
    UPDATED_SUCCESSFULLY: 'Update Reward successfully!',
    GET_DATA_SUCCESSFULLY: 'Get Reward data successfully!',
    DELETED_SUCCESSFULLY: 'Delete Reward successfully!',
  },
  HISTORY_REWARD: {
    NOT_EXIST: "HistoryReward isn't exist.",
    EXISTED: "HistoryReward's name exists.",
    CREATED_SUCCESSFULLY: 'Create HistoryReward successfully!',
    UPDATED_SUCCESSFULLY: 'Update HistoryReward successfully!',
    GET_DATA_SUCCESSFULLY: 'Get HistoryReward data successfully!',
    DELETED_SUCCESSFULLY: 'Delete HistoryReward successfully!',
  },
};
